server:
  port: 8080
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - flyway-entity
      - rabbit
      - mysql
      - redis
      - log
      - security
      - cookie